# Generated by Django 4.1.10 on 2024-01-01 11:24

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CATEGORY_PROD', 'CATEGORY_PRODUCT'), ('HERO_IMAGE', 'HERO_IMAGE'), ('STICKY_NOTES', 'STICKY_NOTES'), ('BRAND_BANNER', 'BRAND_BANNER')], max_length=255)),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_Heading', models.CharField(blank=True, max_length=255, null=True)),
                ('block_name', models.CharField(max_length=255, validators=[api.models.no_whitespace_validator])),
                ('sequence', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
