# Generated by Django 4.1.10 on 2024-01-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_homepageblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageblock',
            name='Card_In_A_Row',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepageblock',
            name='product_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homepageblock',
            name='slider',
            field=models.BooleanField(default=False),
        ),
    ]
