# Generated by Django 4.1.10 on 2024-01-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_homepageblock_card_in_a_row_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageblock',
            name='sequence',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='homepageblock',
            name='type',
            field=models.CharField(choices=[('HERO_IMAGE', 'HERO_IMAGE'), ('CATEGORY_PRODUCT', 'CATEGORY_PRODUCT'), ('STICKY_NOTES', 'STICKY_NOTES')], max_length=255),
        ),
    ]
