# Generated by Django 4.1.10 on 2024-01-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_banners_banner_image_banners_banner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='button_URL',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
