# Generated by Django 4.1.10 on 2024-01-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_banners_button_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='sequence',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
