# Generated by Django 4.1.10 on 2024-02-05 20:02

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_banners_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='relation',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'type__in': ['HERO_IMAGE', 'STICKY_NOTES']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.homepageblock'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='width',
            field=models.CharField(choices=[('3', '25 %'), ('4', '33.33 %'), ('6', '50 %'), ('9', '75 %'), ('12', 'full')], default='12', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=api.models.get_default_product_category, on_delete=models.SET(api.models.get_default_product_category), to='api.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, default=api.models.get_default_product_sub_category, null=True, on_delete=models.SET(api.models.get_default_product_sub_category), to='api.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=api.models.get_default_product_category, on_delete=models.SET(api.models.get_default_product_category), to='api.category'),
        ),
    ]
